#!/bin/sh
# update & upgrade #
sudo apt-get update -y
sudo apt-get upgrade -y
# Essentials
sudo apt install net-tools -y
sudo add-apt-repository ppa:gnome-terminator
sudo apt-get update -y
sudo apt-get install terminator -y
sudo apt-get install code -y
sudo apt-get install hardinfo -y
sudo apt-get install wget
wget https://raw.githubusercontent.com/pimlie/ubuntu-mainline-kernel.sh/master/ubuntu-mainline-kernel.sh
chmod +x ubuntu-mainline-kernel.sh
sudo mv ubuntu-mainline-kernel.sh /usr/local/bin/

# ROS Melodic
sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
sudo apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
sudo apt update
sudo apt install ros-melodic-desktop-full -y
sudo apt install ros-melodic-mir -y
sudo apt install ros-melodic-slam-navigation -y
sudo apt install ros-melodic-mir-robot -y
sudo apt install ros-melodic-navigation -y
echo "source /opt/ros/melodic/setup.bash" >> ~/.bashrc
source ~/.bashrc
sudo apt install python-rosdep python-rosinstall python-rosinstall-generator python-wstool build-essential -y
sudo apt install python-rosdep -y
sudo rosdep init
rosdep update
mkdir -p ~/catkin_ws/src
cd ~/catkin_ws/
source ~/.bashrc
source ~/catkin_ws/devel/setup.bash
catkin_make

echo "source ~/catkin_ws/devel/setup.bash" >> ~/.bashrc
