#!/bin/sh
# update & upgrade #
sudo apt-get update -y
sudo apt-get upgrade -y

# Essentials
sudo apt install net-tools -y
#sudo add-apt-repository ppa:gnome-terminator
sudo apt-get install terminator -y
sudo snap install --classic code -y
sudo apt-get install hardinfo -y

#Install catkin tools for "catkin build"
sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu `lsb_release -sc` main" > /etc/apt/sources.list.d/ros-latest.list'
wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
sudo apt-get update -y
sudo apt-get install python-catkin-tools -y
sudo apt-get install wget -y
sudo apt-get install openssh-server -y
sudo apt install software-properties-common apt-transport-https wget
wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | sudo apt-key add -
wget https://raw.githubusercontent.com/pimlie/ubuntu-mainline-kernel.sh/master/ubuntu-mainline-kernel.sh
sudo add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
sudo apt install code
chmod +x ubuntu-mainline-kernel.sh
sudo mv ubuntu-mainline-kernel.sh /usr/local/bin/

# ROS Melodic
sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
#sudo apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
sudo apt install curl # if you haven't already installed curl
curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
sudo apt update
sudo apt install ros-noetic-desktop-full -y
sudo apt install ros-noetic-mir -y
sudo apt install ros-noetic-slam-navigation -y
sudo apt install ros-noetic-mir-robot -y
sudo apt install ros-noetic-navigation -y
echo "source /opt/ros/noetic/setup.bash" >> ~/.bashrc
echo "export GAZEBO_MODEL_PATH=/usr/share/gazebo-9"  >> ~/.bashrc
source ~/.bashrc
#sudo apt install python-rosdep python-rosinstall python-rosinstall-generator python-wstool build-essential -y
sudo apt install python3-rosdep -y
sudo apt install python3-catkin-tools python3-osrf-pycommon
sudo rosdep init
rosdep update
mkdir -p ~/catkin_ws/src
cd ~/catkin_ws/
source ~/.bashrc
source /opt/ros/noetic/setup.bash


catkin build
source ~/catkin_ws/devel/setup.bash
echo "source ~/catkin_ws/devel/setup.bash" >> ~/.bashrc
cp .startup_shell_text.sh ./
cp .font.txt ./

echo "./.startup_shell_text.sh" >> ~/.bashrc
